name: Notify on Pull Request

on:
  workflow_run:
    workflows: ['Build & Test']
    types:
      - completed

permissions:
  contents: read

jobs:
  # Notificar en Slack cuando se crea un nuevo Pull Request
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TECHNICAL_LEADER: ${{ secrets.TECHNICAL_LEADER }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          --data '{
            "attachments": [
              {
                "pretext": "[Importante] ${{github.event.pull_request.user.login}} Ha creado un nuevo Pull Request: <${{ github.event.pull_request.html_url }}|Revisa aquí>",
                "color": "#137b28ff",
                "fields": [
                  {
                    "title": "${{ github.event.pull_request.title }}",
                    "value": "<@'$TECHNICAL_LEADER'>",
                    "short": false
                  },
                ]
              }
            ]
          }' \
          $SLACK_WEBHOOK_URL
