# Nombre del flujo de trabajo
name: workflow

# Cuando se debe ejecutar el flujo de trabajo
on:
  pull_request:
    types:
      - opened
    branches:
      - release
      - staging

# Permisos para el flujo de trabajo
permissions:
  contents: write

# Se definen los trabajos que se ejecutarán
jobs:
  build:
    name: "Se compila el proyecto"
    runs-on: ubuntu-latest
    steps:
      - name: Subir el código
        uses: actions/checkout@v5

      - name: Instalar pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar tests
        run: pnpm test

      - name: Chequear errores de TypeScript
        run: pnpm test

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Nuevo Pull Request: ${{ github.event.pull_request.title }} por ${{ github.event.pull_request.user.login }}"}' \
            $SLACK_WEBHOOK_URL
