# Nombre del flujo de trabajo
name: workflow

# Cuando se debe ejecutar el flujo de trabajo
on:
  pull_request:
    branches:
      - develop
      - master

# Permisos para el flujo de trabajo
permissions:
  contents: write

# Se definen los trabajos que se ejecutarán
jobs:
  build:
    name: 'Se compila el proyecto'
    runs-on: ubuntu-latest
    steps:
      - name: Subir el código
        uses: actions/checkout@v5

      - name: Instalar pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar tests
        run: pnpm test

      - name: Chequear errores de TypeScript
        run: pnpm test
